# Generated by Django 5.2.6 on 2025-12-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('incomplete', 'Incomplete'), ('complete', 'Complete'), ('canceled', 'Canceled')], default='reserved', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='student_id',
            field=models.CharField(max_length=20),
        ),
    ]
