# Generated by Django 5.2.6 on 2025-10-28 22:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_options_appointment_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_active_faculty_slot',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('incomplete', 'Incomplete'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='reserved', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('faculty', 'date', 'time'), name='unique_active_faculty_slot'),
        ),
    ]
